Footer - Lofi
nwplus/nwhacks2021 pull request #5
Opened 2020-10-25 01:06 UTC by rmehri01

## :construction_worker: Changes

- Removed old background graphics
- Changed text to one in figma

## :flashlight: Testing Instructions

- Amplify!

2020-10-30 02:04 UTC, michaelfromyeg requested changes
Overall looks good! Just in the copyright text at the bottom, it still says UBC LHD 2020.

Also, I think the "made with love" might be one of those components that rotates images of like our faces or something, so it might be good to put in a stub for that for now, but it's lofi so not super needed!

2020-11-01 04:16 UTC, rmehri01 commented
> Overall looks good! Just in the copyright text at the bottom, it still says UBC LHD 2020.
> 
> Also, I think the "made with love" might be one of those components that rotates images of like our faces or something, so it might be good to put in a stub for that for now, but it's lofi so not super needed!

Oh yeah word I'll change that, good catch! I think that the made with love section can be left to the hifi for now.

2020-11-03 06:30 UTC, ItsAdel approved these changes

2020-11-03 06:40 UTC, michaelfromyeg approved these changes
🚀

2020-11-03 07:32 UTC, merged